[package]
name = "octowhere"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-hal = { version = "1.2.2", features = ["esp32s3", "requires-unstable", "unstable"] }
esp-rtos = { version = "0.4.0", features = ["esp32s3", "embassy", "esp-alloc"] }
esp-alloc = { version = "0.11.0", features = ["nightly"] }
esp-println = { version = "0.18.0", features = ["esp32s3", "defmt-espflash"] }
esp-backtrace = { version = "0.20.0", features = ["esp32s3", "panic-handler", "defmt"] }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32s3"] }
log = "0.4"
defmt = "1.0.1"

# Allows for truly statically allocated tasks instead of a bump allocator
embassy-executor = { version = "0.10.0", features = ["nightly"] }
embassy-time = { version = "0.5.1", features = ["defmt-timestamp-uptime-us"] }
embassy-sync = "0.8"
embassy-futures = "0.1"
static_cell = { version = "2.1", features = ["nightly"] }

embedded-graphics = { version = "0.8", features = [] }
embedded-graphics-core = "0.4"

embedded-hal = "1.0"
embedded-hal-bus = { version = "0.3", features = ["async"] }
embedded-hal-async = "1.0.0"
lc76g = { path = "crates/lc76g" }
sx127xlora = { path = "crates/sx127x-lora", features = ["defmt"] }
embedded-io-async = "0.7"
futures = { version = "0.3.32", default-features = false, features = ["async-await"] }
embassy-embedded-hal = "0.6.0"
ph-qmi8658 = { version = "0.1.1", features = ["fixed"] }
tca9554 = "0.2.0"
heapless = { version = "0.9.3", features = ["nightly"] }
fontdue = { version = "0.9.3", default-features = false, features = ["hashbrown"] }
fontdue-macros = "0.9.3"
embedded-layout = "0.4.2"

[features]
default = []
damage-debug = []
timing-log = []
gnss-raw-log = []
gnss-full-power = []
fontdue-target-bench = []
fontdue-target-bench-gcc = ["fontdue-target-bench"]
lora-link-tx = []
lora-link-rx = []

[patch.crates-io]
tca9554 = { git = "https://github.com/CordlessCoder/tca9554-rs", rev = "dd76e69" }
fontdue = { git = "https://github.com/CordlessCoder/fontdue", rev = "7678d10ea76791beb96415855dc774e5d53a7775" }
fontdue-macros = { git = "https://github.com/CordlessCoder/fontdue", rev = "7678d10ea76791beb96415855dc774e5d53a7775" }

[profile.dev]
opt-level = "s"
lto = "thin"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
debug = true
